version: '3'
services:
  bingo:
    build: .
    volumes:
      - .:/app
    environment:
      - DISPLAY=$DISPLAY  # For screen capture functionality
    # Add this for Windows with WSL
    # - DISPLAY=host.docker.internal:0